name: Teardown SSH agent
description: "A composite action to clean up credentials and configurations from the SSH agent after use."
author: Dr. Kibitz (@drkibitz)

runs:
  using: composite
  steps:
    - name: Teardown SSH agent
      if: always()
      run: |
        ssh-add -D
        rm -rf ~/.ssh/
      shell: bash
