name: Teardown SSH
description: "A composite action to clean up SSH credentials and configurations after use."
author: Dr. Kibitz (@drkibitz)

runs:
  using: composite
  steps:
    - name: Teardown SSH
      if: always()
      run: |
        ssh-add -D
        rm -rf ~/.ssh/
      shell: bash
